#CONFIGURATION FILE

ExcelFilesOutputPath=C:/Users/arek4/OneDrive/Pulpit(1)/ProjektNaZakladProd/ExeleDoTestow/

ExcelFilesInputPath=C:/Users/arek4/OneDrive/Pulpit(1)/ProjektNaZakladProd/CzysteArkuszeExcel/

FolderWithPDFs=C:/Users/arek4/OneDrive/Pulpit(1)/ProjektNaZakladProd/PDFs/