spring.application.name=ListManagementApp
spring.profiles.active=dev
spring.config.name=application
server.port=8080
server.address=localhost
spring.datasource.url=jdbc:sqlite:C:/Softs/ProjektDlaStarego/ListManagmentApp/src/main/resources/JsonBuffer
spring.docker.compose.enabled=false
