spring.application.name=ListManagmentApp
spring.profiles.active=dev
spring.config.name=application
server.port=8080
server.address=localhost
spring.datasource.url=jdbc:sqlite:C:/Softs/ProjektDlaStarego/ListManagmentApp/src/main/resources/JsonBuffer/main/tables/Tabela.db
spring.docker.compose.enabled=false
